version: '3.8'

services:
  complaint-ui:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=https://www.backend-complaint.com
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G 